kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-mongo-pv
  namespace: services
  labels:
    type: cam-mongo
spec:
  capacity:
    storage: 15Gi
  accessModes:
    -  ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /storage/CAM_dbs
